name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: 'wordpress_test'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      DB_HOST: 127.0.0.1
      DB_NAME: wordpress_test
      DB_USER: root
      DB_PASSWORD: 'root'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mysql, mysqli
          coverage: xdebug

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Setup WordPress Test Environment
        run: bash bin/install-wp-tests.sh ${{ env.DB_NAME }} ${{ env.DB_USER }} "${{ env.DB_PASSWORD }}" ${{ env.DB_HOST }} latest true

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Audit NPM Dependencies
        run: npm audit --audit-level=high

      - name: Audit Composer Dependencies
        run: composer audit

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --coverage-text --exclude-group=ignore-ci/cd
